### ISSUE TITLE
IoC verification failing

### ISSUE THREAD

**Issue by DavidSSL** [DavidSSL/SI-Trial#1]
Git commit point: 60da9e5

This is is the code for the SO Post

When I run this, I get:

```
Unhandled exception. System.InvalidOperationException: The configuration is invalid. Creating the instance for type 
IAmAnS3ClientQueryor failed. The constructor of type S3Queryor contains the parameter with name 's3Client' and type IAmazonS3, 
bu t IAmazonS3 is not registered. For IAmazonS3 to be resolved, it must be registered in the container. There is, however, a 
registration for a collection of IAmazonS3 instances; Did you mean to depend on IEnumerable<IAmazonS3> instead? If you mean t to 
depend on IAmazonS3, you should use one of the Container.Register overloads instead of using Container.Collection.Register. Please 
see https://simpleinjector.org/collections for more information about registering and resolving collections. 
```

Then @dotnetjunkie said in [SO](https://stackoverflow.com/questions/69987358/registering-multiple-amazons3clients-in-simpleinjector-and-configuring-adapter?noredirect=1#comment123720368_69987358) said:

> Why are you registering S3Queryor and the list of IAmazonS3 instances and the s3ClientsQueryors variable in the container anyway? S3FileNamesGetter seems your adapter and it depends (through s3ClientsQueryors) on both S3Queryor instances. If you remove the registrations for S3Queryor the collection of IAmazonS3 and s3ClientsQueryors, things should start to work, because you won't be tripping Simple Injector's validation on those unused registrations.

Hence I tried, to the best of my understanding, what he suggested  (Git commit: dffa82d) but this time I get:

```
Unhandled exception. System.InvalidOperationException: The configuration is invalid. Creating the instance for type IGetFileNames failed. The constructor of type S3FileNamesGetter contains the parameter
with name 's3Clients' and type IDictionary<S3ClientType, IAmAnS3ClientQueryor>, but IDictionary<S3ClientType, IAmAnS3ClientQueryor> is not registered. For IDictionary<S3ClientType, IAmAnS3ClientQueryor>
to be resolved, it must be registered in the container.
 ---> SimpleInjector.ActivationException: The constructor of type S3FileNamesGetter contains the parameter with name 's3Clients' and type IDictionary<S3ClientType, IAmAnS3ClientQueryor>, but IDictionary<
S3ClientType, IAmAnS3ClientQueryor> is not registered. For IDictionary<S3ClientType, IAmAnS3ClientQueryor> to be resolved, it must be registered in the container.
```

However, this seems to be leading me towards what @dotnetjunkie was questioning me about above.

**Comment by dotnetjunkie** [comment]
Would it work for you when you change your `Bootstrap` to the following:

``` c#
internal static class Bootstrap
{
    public static void Start(Container container, RegionEndpoint bucketRegion)
    {
        container.RegisterInstance<IGetFileNames>(new S3FileNamesGetter(
            new Dictionary<S3ClientType, IAmAnS3ClientQueryor>
            {
                {
                    S3ClientType.Discriminator1,
                    new S3Queryor(new AmazonS3Client("apiKey1", "secretKey1", bucketRegion))
                },
                {
                    S3ClientType.Discriminator2,
                    new S3Queryor(new AmazonS3Client("apiKey2", "secretKey2", bucketRegion))
                },
            }));

        container.Options.EnableAutoVerification = false;

        container.Verify();
    }
} 
```

**Comment by DavidSSL** [comment]
@dotnetjunkie this does indeed work for me. However, I am a bit lost in terms of how this is all working. Why is this not asking me to register IAmazonS3 like in commit 60da9e5 ?

**Comment by dotnetjunkie** [comment]
In yhe registration I am propoding, I am circumventing Simple Injector partly to build up part of the objects. That's because itnis not always useful for your DI Container to tie _everyting_ and it is sometimes just simpler to do it (partly) by hand. That's what I did here: I tied them by hand.

Simple Injector's verification feature is rather strict. It assumes that you wish to use  resolve, or inject any component that you registered. That's why it tries to create every registration. That failed in your case, because you registered some components that actually weren't actually ever injected by Simple Injector. Sich component should not be registered, because that causes verification to give of false positives.

**Comment by DavidSSL** [comment]
Thanks for the explanation @dotnetjunkie
